services:
  mysql-dump:
    image: mysql:8.0
    container_name: mysql8-dump
    working_dir: /
    entrypoint: ["/bin/bash", "/usr/local/bin/mysql-dump-on-start.sh"]
    env_file:
      - ./config/mysql/.env
    volumes:
      - ./docker/mysql/mysql-dump-on-start.sh:/usr/local/bin/mysql-dump-on-start.sh:ro
      - ./volumes/mysql8/backup:/backup
      - ./volumes/mysql8/shared:/shared

  mysql-cli:
    image: mysql:8.0
    container_name: mysql-cli
    working_dir: /
    command: /bin/bash
    env_file:
      - ./config/mysql/.env
    volumes:
      - ./volumes/mysql8/backup:/backup
      - ./volumes/mysql8/shared:/shared

  redis-cli:
    image: redis
    container_name: redis-cli
    working_dir: /
    command: /bin/bash
    env_file:
      - ./config/redis/.env.exemple
    volumes:
      - ./volumes/redis/backup:/backup
      - ./volumes/redis/shared:/shared
  postgres16-cli:
    image: postgres:16
    container_name: postgres16-cli
    working_dir: /
    command: /bin/bash
    env_file:
      - ./config/postgres/.env.exemple
    volumes:
      - ./volumes/postgres16/backup:/backup
      - ./volumes/postgres16/shared:/shared
